# ================================================================================
# ========== WELCOME TO THE NEOCOMPILER ECO NEO BLOCKCHAIN MICROSERVICE  =========
# ================================================================================

version: "3"
services:

# ================================================================================
# ================== OPEN CONTAINER WITH NEO-CLI RPC DESIGNED FOR MAINNET ========
  eco-neo-csharp-node1-running:
    image: eco-neo-csharp-node-mainnet:latest
    container_name: "eco-neo-csharp-noderpc-mainnet-testnet"
    # privileged is needed for controlling ifconfig
    privileged: true
    ports: 
      - "10334:10334"
      - "10333:10333"
      - "10332:10332"
    volumes:
      - ./neo-cli/configs/protocol.mainnet.json:/opt/node/neo-cli/protocol.json
      - ./neo-cli/configs/config.mainnet.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/importBlocks.json:/opt/node/neo-cli/Plugins/ImportBlocks/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./Chain:/opt/node/neo-cli/Chain_00746E41
      - ./Storage:/opt/node/neo-cli/Storage
      #- ./chain.0.acc.zip:/opt/node/neo-cli/chain.0.acc.zip
      #- ./chain.0.acc:/opt/node/neo-cli/chain.0.acc
      - ./logs-neocli-nodeRPC:/opt/node/neo-cli/Logs
    environment:
      IS_RPC: 1
      NUMBER_SERVER: 1
      DISABLE_NETWORK_P2P: 0
# ================================================================================
# ======================= THANKS FOR CREATING ME =================================
# ================================================================================
