# ================================================================================
# ========== WELCOME TO THE NEOCOMPILER ECO NEO BLOCKCHAIN MICROSERVICE  =========
# ================================================================================
version: "3.7"
services:
# ================================================================================
# ================== OPEN CONTAINER WITH NEO-CLI RPC DESIGNED FOR MAINNET ========
  eco-neo-csharp-node-assert-base-version:
    image: eco-neo-csharp-node-assert:$NEO_CLI_BASE_VERSION
    container_name: "eco-neo-csharp-node-assert-base-version"
    privileged: true
    ports: 
      - "10334:10334"
      - "10333:10333"
      - "10332:10332"
    volumes:
      - ./neo-cli/configs/protocol.testnet.json:/opt/node/neo-cli/protocol.json
      - ./neo-cli/configs/config.base.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/importBlocks.json:/opt/node/neo-cli/Plugins/ImportBlocks/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/configs/plugins/statesDumper.json:/opt/node/neo-cli/Plugins/StatesDumper/config.json
      - ./neo-cli/configs/plugins/rpcNep5Tracker.json:/opt/node/neo-cli/Plugins/RpcNep5Tracker/config.json
      - ./neo-cli/configs/plugins/rpcSystemAssetTracker.json:/opt/node/neo-cli/Plugins/RpcSystemAssetTracker/config.json
      - ./ChainBase:/opt/node/neo-cli/Chain_74746E41
      - ./StorageBase:/opt/node/neo-cli/Storage
      - ./StorageNew:/opt/node/neo-cli/StorageComp
      - ./chain.acc.zip:/opt/node/neo-cli/chain.acc.zip
      - ./healthcheckScript.sh:/opt/healthcheckScript.sh
    environment:
      IS_CONSENSUS: 0
      IS_RPC: 1
      DISABLE_NETWORK_P2P: 0
    healthcheck:
      test:
        - CMD
        - /opt/healthcheckScript.sh
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s

  eco-neo-csharp-node-assert-new-version:
    image: eco-neo-csharp-node-assert:$NEO_CLI_NEW_VERSION
    container_name: "eco-neo-csharp-node-assert-new-version"
    privileged: true
    ports: 
      - "20334:20334"
      - "20333:20333"
      - "20332:20332"
    volumes:
      - ./neo-cli/configs/protocol.testnet.json:/opt/node/neo-cli/protocol.json
      - ./neo-cli/configs/config.new.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/importBlocks.json:/opt/node/neo-cli/Plugins/ImportBlocks/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/configs/plugins/statesDumper.json:/opt/node/neo-cli/Plugins/StatesDumper/config.json
      - ./neo-cli/configs/plugins/rpcNep5Tracker.json:/opt/node/neo-cli/Plugins/RpcNep5Tracker/config.json
      - ./neo-cli/configs/plugins/rpcSystemAssetTracker.json:/opt/node/neo-cli/Plugins/RpcSystemAssetTracker/config.json
      - ./ChainNew:/opt/node/neo-cli/Chain_74746E41
      - ./StorageNew:/opt/node/neo-cli/Storage
      - ./StorageBase:/opt/node/neo-cli/StorageComp
      - ./chain.acc.zip:/opt/node/neo-cli/chain.acc.zip
      - ./healthcheckScript.sh:/opt/healthcheckScript.sh
    environment:
      IS_CONSENSUS: 0
      IS_RPC: 1
      DISABLE_NETWORK_P2P: 0
    healthcheck:
      test:
        - CMD
        - /opt/healthcheckScript.sh
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
# ================================================================================
# ======================= THANKS FOR CREATING ME =================================
# ================================================================================
